Controllers/EventController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Contrib.Events.Models;
using Orchard.ContentManagement;
using Orchard.DisplayManagement;
using Orchard.Localization;
using Orchard.Logging;
using Orchard.Settings;
using Orchard.Themes;
using Orchard.UI.Navigation;

namespace Contrib.Events.Controllers {
    [Themed]
    public class EventController : Controller {
        private readonly IContentManager _contentManager;
        private readonly ISiteService _siteService;

        public EventController(
            IContentManager contentManager, 
            IShapeFactory shapeFactory,
            ISiteService siteService)
        {
            _contentManager = contentManager;
            _siteService = siteService;
            Logger = NullLogger.Instance;
            Shape = shapeFactory;
            T = NullLocalizer.Instance;
        }

        dynamic Shape { get; set; }
        protected ILogger Logger { get; set; }
        public Localizer T { get; set; }

        public ActionResult List(PagerParameters pagerParameters, int? month) {
            var pager = new Pager(_siteService.GetSiteSettings(), pagerParameters);
            var query = _contentManager.Query<EventPart>(VersionOptions.Published).OrderBy<EventPartRecord>(e => e.StartDate);
            var today = DateTime.Today;

            query = query.Where(e => e.EndDate >= today);

            if (month.HasValue) {
                var filterDate = new DateTime(today.Year, month.Value, today.Day);
                var filterEndDate = filterDate.AddMonths(1).AddDays(2 - filterDate.Day);

                if (filterDate < today) {
                    filterDate = filterDate.AddYears(1);
                }

                if (filterDate.Month != today.Month) {
                    filterDate = filterDate.AddDays(1 - filterDate.Day);
                }

                query = query.Where(e => (e.StartDate.Value.Date <= filterDate && filterDate < e.EndDate.Value.Date) || (e.StartDate.Value.Date <= filterEndDate && filterEndDate < e.EndDate.Value.Date));
            }

            query = query.OrderBy(x => x.StartDate);

            var pageOfEvents = query.Slice(pager.GetStartIndex(), pager.PageSize).ToList();

            var search = _contentManager.New("EventSearch");
            search.Weld(new EventSearchPart());

            var searchShape = _contentManager.BuildDisplay(search);

            var list = Shape.List();
            list.AddRange(pageOfEvents.Select(e => _contentManager.BuildDisplay(e, "Summary")));

            dynamic viewModel = Shape.ViewModel()
                .EventSearch(searchShape.EventSearch)
                .Months(Enumerable.Range(1,12))
                .ContentItems(list)
                .Pager(Shape.Pager(pager).TotalItemCount(query.Count()));

            //searchShape.viewModel = viewModel;

            return View(viewModel);
        }
    }
}

Views/Content-Event.SummaryAdmin.cshtml
@using Orchard.ContentManagement;
@using Orchard.Core.Contents
@using Orchard.Utility.Extensions;
@{
    ContentItem contentItem = Model.ContentItem;
    var returnUrl = ViewContext.RequestContext.HttpContext.Request.ToUrlString();
}
<div class="summary" itemscope="itemscope" itemid="@contentItem.Id" itemtype="http://orchardproject.net/data/ContentItem">
    <div class="properties">
        <input type="checkbox" value="@contentItem.Id" name="itemIds" />
        <h3>@Html.ItemAdminLink(contentItem)</h3> - <div class="contentType">@contentItem.TypeDefinition.DisplayName</div>
        @if (Model.Header != null)
        {
            <div class="header">@Display(Model.Header)</div>
        }
        @if (Model.Meta != null)
        {
            <div class="metadata">@Display(Model.Meta)</div>
        }
    </div>
    <div class="related">
        @Display(Model.Actions)
        @if (Authorizer.Authorize(Permissions.EditContent, contentItem))
        {
            @Html.ItemEditLinkWithReturnUrl(T("Edit").Text, contentItem)@T(" | ")
        }
        @if (Authorizer.Authorize(Permissions.DeleteContent, contentItem))
        {
            @Html.Link(T("Delete").Text, Url.ItemRemoveUrl(contentItem, new { returnUrl }), new { itemprop = "RemoveUrl UnsafeUrl" })
        }
    </div>
    @if (Model.Content != null)
    {
        <div class="primary">@Display(Model.Content)</div>
    }
</div>

Views/Parts.Event.Detail.cshtml
@using Contrib.Events.ViewModels;
@{
    var eventModel = Model.ContentItem.EventPart;
    Script.Require("jQuery");
    Script.Require("GoogleMaps");
    Style.Require("Events_Detail");
}

<div class="event">
    <div class="event-date">
        @Display.DateTime(DateTimeUtc: eventModel.StartDate, CustomFormat: T("D"))

        @if (eventModel.StartDate.Date != eventModel.EndDate.Date)
        {
            @:- @Display.DateTime(DateTimeUtc: eventModel.EndDate, CustomFormat: T("D"))
        }
    </div>

    <div class="event-info">
        <div class="event-exactLocation">
            <dl>
                <dt>Address</dt>
                <dd>
                    <div class="event-address">
                        @if (!String.IsNullOrWhiteSpace(eventModel.Address))
                        {
                            @eventModel.Address <br />
                        }

                        @if (!String.IsNullOrWhiteSpace(eventModel.AdditionalAddressInfo))
                        {
                            @eventModel.AdditionalAddressInfo <br />
                        }

                        @eventModel.CityStateZip
                    </div>
                </dd>
            </dl>
        </div>

        @if (!String.IsNullOrWhiteSpace("" + eventModel.ContactName + eventModel.ContactEmail + eventModel.ContactPhone))
        {
            <div class="event-contact">
                @if (!String.IsNullOrWhiteSpace(eventModel.ContactName))
                {
                    <dl class="event-contactName">
                        <dt>Contact: </dt>
                        <dd>@eventModel.ContactName</dd>
                    </dl>
                }
                @if (!String.IsNullOrWhiteSpace(eventModel.ContactPhone))
                {
                    <dl>
                        <dt>Phone: </dt>
                        <dd>@eventModel.ContactPhone</dd>
                    </dl>
                }
                @if (!String.IsNullOrWhiteSpace(eventModel.ContactEmail))
                {
                    <dl>
                        <dt>Email: </dt>
                        <dd>@eventModel.ContactEmail</dd>
                    </dl>
                }
            </div>
        }    
    </div>
    
    @if (eventModel.HasCoordinates) {
    <div class="event-googleMap">
        <div class="event-googleMapCanvas"></div>
    </div>
    }
</div>

@using (Script.Foot()) {
    if (eventModel.HasCoordinates) {
         <script type="text/javascript">
             $(function () {
                 var mapElement = $(".event-googleMapCanvas");
                 var latitude = "@eventModel.GpsLat";
                 var longitude = "@eventModel.GpsLng";
                 if (mapElement.length > 0) {
                     var latLng = new google.maps.LatLng(latitude, longitude);

                     var myOptions = {
                         center: latLng,
                         zoom: 7,
                         mapTypeId: google.maps.MapTypeId.ROADMAP
                     };

                     var map = new google.maps.Map(mapElement.get(0), myOptions);

                     var marker = new google.maps.Marker({
                         position: latLng,
                         animation: google.maps.Animation.DROP,
                         map: map
                     });
                 } else {
                     //No map object, so don't bother
                 }
             })
    
         </script>
     }
}

Views/Parts.Event.Metadata.SummaryAdmin.cshtml
@using Contrib.Events.Models;
@{
    EventPart eventPart = Model.ContentPart;
}
<ul class="pageStatus">
    @* Future *@
    @if (eventPart.StartDate > DateTime.Now)
    {
        <li><img class="icon" src="@Href("~/Modules/Contrib.Events/Content/Admin/images/future.gif")" alt="@T("Upcoming")" title="@T("The event is upcoming")" /> </li>
        <li> @T("Starting {0}", Display.DateTimeRelative(dateTimeUtc: eventPart.StartDate))&nbsp;&#124;&nbsp;</li>
    }
    @* Current *@
    else if (eventPart.EndDate > DateTime.Now)
    {
        <li><img class="icon" src="@Href("~/Modules/Contrib.Events/Content/Admin/images/current.gif")" alt="@T("Current")" title="@T("The event is currently active")" /> </li>
        <li>@T("Ending {0}", Display.DateTimeRelative(dateTimeUtc: eventPart.EndDate))&nbsp;&#124;&nbsp;</li>
    }
    @* Past *@
    else
    {
        <li><img class="icon" src="@Href("~/Modules/Contrib.Events/Content/Admin/images/Past.gif")" alt="@T("Ended")" title="@T("The event is Past")" /> </li>
        <li>@T("Ended {0}", Display.DateTimeRelative(dateTimeUtc: eventPart.EndDate))&nbsp;&#124;&nbsp;</li>
    }
</ul>

Views/Parts.Event.Summary.cshtml
@using Contrib.Events.Models;
@{
    EventPart eventPart = Model.ContentPart;
}

<div>
    @Display.DateTime(DateTimeUtc: eventPart.StartDate.Value, CustomFormat: T("MMM dd, yyyy"))

    @if (eventPart.StartDate.Value.ToLocalTime().Date != eventPart.EndDate.Value.ToLocalTime().Date)
    {
        @:- @Display.DateTime(DateTimeUtc: eventPart.EndDate.Value, CustomFormat: T("MMM dd, yyyy"))
    }
</div>

Views/Parts.EventSearch.cshtml
@using (Html.BeginForm("List", "Event", new { Area = "Contrib.Events" }, FormMethod.Get, new { @class = "search-form" }))
{
    <fieldset>
        @Html.Label("keywords", "Keywords")
        @Html.TextBox("keywords")

        @Html.Label("startDate", "Start Date")
                @Html.TextBox("startDate", null, new { type = "date" })

        @Html.Label("endDate", "End Date")
        @Html.TextBox("endDate", null, new { type = "date" })

        <button type="submit">@T("Search")</button>
    </fieldset>
}